//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QBuild
{
    using System;
    using System.Collections.Generic;
    
    public partial class bmo
    {
        public int Id { get; set; }
        public string PARENT_NAME { get; set; }
        public string QUANTITY { get; set; }
        public string COMPONENT_NAME { get; set; }
    }
}
